db:
  image: jamesbrink/postgresql
  environment:
    - SCHEMA=example
    - USER=example
    - PASSWORD=password
    - POSTGIS=true

rediscache:
  image: redis:latest

rediscelery:
  image: redis:latest
  volumes_from:
    - data

app:
  build: .
  command: /usr/bin/supervisord -n
  volumes:
    - ./docker_config/supervisor.conf:/etc/supervisor/conf.d/myconf.conf
    - ./docker_config/start.sh:/code/start.sh
    - ./docker_config/start_cel.sh:/code/start_cel.sh
    - ./project:/code
  volumes_from:
    - data
  links:
    - db
    - rediscache
    - rediscelery

nginx:
  image: nginx:latest
  volumes:
    - ./docker_config/myconf.nginx:/etc/nginx/nginx.conf
  volumes_from:
    - data
  ports:
    - "80:80"
  links:
    - app
